In [ ]:
#Mount data from drive
from google.colab import drive
drive.mount('/content/Drive')

Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).

In [ ]:
import os
os.listdir('/content/Drive')

['.shortcut-targets-by-id', 'MyDrive', '.file-revisions-by-id', '.Trash']

In [ ]:
import numpy as np
import pandas as pd
import matplotlib

import matplotlib.pyplot as plt


import matplotlib.mlab as mlab
import seaborn as sb

%matplotlib inline

In [ ]:
#read data from drive folder
data = pd.read_csv('Drive/My Drive/Dataset/MERGED2005_06_PP.csv')
data

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

      Unnamed: 0    UNITID     OPEID  ...  CIPTFBS6   UG12MN   G12MN
0              0    100636   1230800  ...       NaN      NaN     NaN
1              1    100654    100200  ...       NaN   7121.0  2330.0
2              2    100663    105200  ...       NaN  13877.0  6601.0
3              3    100690   2503400  ...       NaN    538.0   489.0
4              4    100706    105500  ...       NaN   6578.0  1788.0
...          ...       ...       ...  ...       ...      ...     ...
6894        6894  43821203  00489805  ...       NaN      NaN     NaN
6895        6895  44098901  02568108  ...       NaN      NaN     NaN
6896        6896  44098902  02568101  ...       NaN      NaN     NaN
6897        6897  44098903  02568106  ...       NaN      NaN     NaN
6898        6898  44098904  02568107  ...       NaN      NaN     NaN

[6899 rows x 1462 columns]

**Drop All Null Columns & Rows whose all values are NULL**

---

In [ ]:
df = data.dropna(how='all', axis=1)
df = df.dropna(how='all')
df

        UNITID     OPEID  OPEID6  ... CIPTFBS6   UG12MN   G12MN
0       100636   1230800   12308  ...      NaN      NaN     NaN
1       100654    100200    1002  ...      NaN   7121.0  2330.0
2       100663    105200    1052  ...      NaN  13877.0  6601.0
3       100690   2503400   25034  ...      NaN    538.0   489.0
4       100706    105500    1055  ...      NaN   6578.0  1788.0
...        ...       ...     ...  ...      ...      ...     ...
6894  43821203  00489805    4898  ...      NaN      NaN     NaN
6895  44098901  02568108   25681  ...      NaN      NaN     NaN
6896  44098902  02568101   25681  ...      NaN      NaN     NaN
6897  44098903  02568106   25681  ...      NaN      NaN     NaN
6898  44098904  02568107   25681  ...      NaN      NaN     NaN

[6899 rows x 1461 columns]

**Remove duplicate rows who have all NUll entries and all those rows who has to be unique value as column**

In [ ]:
df = df.drop_duplicates()
df = df.drop_duplicates(subset=['UNITID','OPEID','OPEID6'])
df

      UNITID     OPEID  OPEID6  ... CIPTFBS6   UG12MN   G12MN
0     100636  01230800   12308  ...      NaN      NaN     NaN
1     100654  00100200    1002  ...      NaN   5447.0  1665.0
2     100663  00105200    1052  ...      NaN  13129.0  6399.0
3     100690  02503400   25034  ...      NaN    411.0   386.0
4     100706  00105500    1055  ...      NaN   6678.0  1776.0
...      ...       ...     ...  ...      ...      ...     ...
6668  444042  02260602   22606  ...      NaN    118.0     NaN
6669  444051  03319301   33193  ...   1720.0    159.0     NaN
6670  444060  00754805    7548  ...      NaN      NaN     NaN
6671  444079  03434301   34343  ...   3195.0     15.0     NaN
6672  444088  02218808   22188  ...      NaN    138.0     NaN

[6673 rows x 1251 columns]

**Check if any Column have same single value**

In [ ]:
res=df
for col in df.columns:
    if len(df[col].unique()) == 1:
        res = res.drop([col],axis=1)
res

      UNITID     OPEID  OPEID6  ... CIPTFBS6   UG12MN   G12MN
0     100636  01230800   12308  ...      NaN      NaN     NaN
1     100654  00100200    1002  ...      NaN   5447.0  1665.0
2     100663  00105200    1052  ...      NaN  13129.0  6399.0
3     100690  02503400   25034  ...      NaN    411.0   386.0
4     100706  00105500    1055  ...      NaN   6678.0  1776.0
...      ...       ...     ...  ...      ...      ...     ...
6668  444042  02260602   22606  ...      NaN    118.0     NaN
6669  444051  03319301   33193  ...   1720.0    159.0     NaN
6670  444060  00754805    7548  ...      NaN      NaN     NaN
6671  444079  03434301   34343  ...   3195.0     15.0     NaN
6672  444088  02218808   22188  ...      NaN    138.0     NaN

[6673 rows x 1251 columns]

In [ ]:
df.to_csv('Drive/My Drive/Dataset/MERGED2005_06_PP.csv')